# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"architecture_config": "00_yolov1.ipynb",
         "CNNBlock": "00_yolov1.ipynb",
         "YoloV1": "00_yolov1.ipynb"}

modules = ["yolov1.py"]

doc_url = "https://ioannispol.github.io/proejct_demo/"

git_url = "https://github.com/ioannispol/proejct_demo/tree/master/"

def custom_doc_links(name): return None
